main:
  method: 'get'
  path: ~
  controller: App\Movie\Controller\HomeController
  action: index

show:
  method: 'get'
  path: 'movie/{id}'
  controller: App\Movie\Controller\ShowController
  action: show
